FROM node:lts-alpine
WORKDIR /app

# Instala pnpm globalmente
RUN npm install -g pnpm

# Copia solo package.json para instalar dependencias
COPY package*.json ./
RUN pnpm install

# Montaremos el resto con volumen, así que no copiamos todo
EXPOSE 5173
CMD ["pnpm", "dev"]